### ISSUE TITLE
Add an open-source license

### ISSUE THREAD

**Issue by Pathoschild** [bmarquismarkail/SV_BetterQualityMoreSeeds#3]
This mod broke in recent versions of the game, but technically other modders can't help update it since you don't have a code license. Can you [choose an open-source license](https://choosealicense.com/) and [add a `LICENSE` file to the repository](https://help.github.com/en/articles/adding-a-license-to-a-repository)? (MIT is a good choice if you're not sure.)

See _[open source](https://stardewvalleywiki.com/Modding:Open_source)_ on the wiki for more info.

**Comment by bmarquismarkail** [comment]
Well

I usually go for the GPL Lesser, but at the time it would be hard to get in touch with me, so MIT is fine.
